-- Re-sync every identity/serial sequence in `public` to the highest id present.
--
-- Needed after a restore: rows inserted with explicit ids (seed data, imports,
-- an earlier restore) do not advance a `GENERATED BY DEFAULT` identity
-- sequence, so `pg_dump` faithfully records the stale value — e.g.
-- `setval('public.sections_id_seq', 1, false)` next to six existing rows. The
-- first insert after such a restore then fails on a duplicate primary key.
--
-- Safe to run at any time: it only ever moves a sequence up to max(id).

do $$
declare
  r record;
  max_id bigint;
begin
  for r in
    select
      c.table_schema,
      c.table_name,
      c.column_name,
      pg_get_serial_sequence(format('%I.%I', c.table_schema, c.table_name), c.column_name) as seq_name
    from information_schema.columns c
    where c.table_schema = 'public'
      and pg_get_serial_sequence(format('%I.%I', c.table_schema, c.table_name), c.column_name) is not null
    order by c.table_name, c.column_name
  loop
    execute format('select coalesce(max(%I), 0) from %I.%I', r.column_name, r.table_schema, r.table_name)
      into max_id;

    -- is_called = false when the table is empty, so the first id stays 1
    perform setval(r.seq_name, greatest(max_id, 1), max_id > 0);

    raise notice 'resync % -> % (max id %)', r.seq_name, greatest(max_id, 1), max_id;
  end loop;
end $$;
