#!/usr/bin/env bash
#
# Restore a backup's DATA into the local Supabase database, on top of a schema
# built from supabase/migrations/.
#
# The schema deliberately does NOT come from the backup: `supabase db reset`
# rebuilds it from the migrations in this repository, so a restored database is
# always at the current schema version. That is what makes this script safe to
# use with old backups — there is no list of migrations to keep up to date.
#
# Usage: scripts/db-restore-local.sh <backup-dir>

set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <backup-dir>"
  echo "Example: $0 backups/supabase/2026-04-17_18-30-00"
  exit 1
fi

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BACKUP_DIR="$1"

if [[ "$BACKUP_DIR" != /* ]]; then
  BACKUP_DIR="$ROOT_DIR/$BACKUP_DIR"
fi

DATA_FILE="$BACKUP_DIR/data.sql"
PSQL_IMAGE="${PSQL_IMAGE:-postgres:17-alpine}"

if [[ ! -f "$DATA_FILE" ]]; then
  echo "Data file not found: $DATA_FILE"
  echo "Required: data.sql (schema.sql is not used — the schema comes from supabase/migrations/)"
  exit 1
fi

cd "$ROOT_DIR"

echo "Starting local Supabase if needed..."
npx supabase start >/dev/null

echo "Rebuilding the local schema from supabase/migrations/ (no seed data)..."
npx supabase db reset --no-seed

echo "Resolving local DB URL..."
DB_URL="$(npx supabase status -o env | awk -F= '/^DB_URL=/{gsub(/\"/, "", $2); print $2}')"

if [[ -z "$DB_URL" ]]; then
  echo "Could not determine local DB URL from 'supabase status -o env'."
  exit 1
fi

echo "Loading data from $BACKUP_DIR/data.sql ..."
# The dump begins with `SET session_replication_role = replica`, so triggers and
# foreign keys do not fire during the load and table order does not matter.
docker run --rm --network host -v "$BACKUP_DIR:/backup:ro" "$PSQL_IMAGE" \
  psql "$DB_URL" -v ON_ERROR_STOP=1 -f /backup/data.sql

echo "Re-syncing identity sequences to the restored data..."
# Dumps can carry stale sequence values (rows inserted with explicit ids never
# advance a GENERATED BY DEFAULT identity), which makes the first insert after a
# restore fail on a duplicate key.
docker run --rm --network host -v "$ROOT_DIR:/repo:ro" "$PSQL_IMAGE" \
  psql "$DB_URL" -v ON_ERROR_STOP=1 -q -f /repo/scripts/sql/resync_sequences.sql

echo
echo "Local restore complete — schema from migrations, data from the backup."
echo "Open Supabase Studio: http://127.0.0.1:54323"
echo
echo "If the backup's user IDs differ from the local auth users, repoint ownership with:"
echo "  select public.reassign_profile_user('<old-user-id>'::uuid, '<new-auth-user-id>'::uuid, true);"
